### ISSUE TITLE
[NEW GOAL] Turn a Pig into Zombified Piglin

### ISSUE THREAD

**Issue by rybak** [Joshimuz/mcbingo#33]
**Name of the Goal**
"Turn a Pig into Zombified Piglin"

**Difficulty level**
Very Hard. Requires thunderstorm weather and a Trident with Channeling to generate lightning. See https://minecraft.gamepedia.com/Pig#Behavior

["Trident"](https://minecraft.gamepedia.com/Trident#Obtaining) is [currently a "Hard" goal](https://github.com/Joshimuz/mcbingo/blob/master/goals_v4.js#L434).

**Why this Goal is good**
Using lightning on mobs is a niche game mechanic. Most of the players which are aware of it only know about turning Creepers into Charged Creepers.

**Comment by rybak** [comment]
Also: https://twitter.com/notch/status/57426954093211648

**Comment by rybak** [comment]
A variation of this goal could be "Turn a piglet into a baby Zombified Piglin". It is even harder, because it requires breeding pigs.

**Comment by Joshimuz** [comment]
Just normal Pig is hard enough I would think, added
