### ISSUE TITLE
[NEW GOAL] Sleep in every colour of Bed

### ISSUE THREAD

**Issue by rybak** [Joshimuz/mcbingo#44]
**Name of the Goal**
Sleep in every colour of Bed.

**Tooltip for the Goal**
"Black, Blue, Brown, Cyan, Grey, Green, Light Blue, Light Grey, Lime, Magenta, Orange, Pink, Purple, Red, White and Yellow!""

**Difficulty level**
Hard or Very Hard. Because Beds can be found in Villages, it doesn't require finding every colour of Dye.

**Anti Synergies and Catalysts/Reactants**
Goal "Every colour of Dye" is already in Very Hard difficulty.

**Why this Goal is good**
Sleeping in 16 Beds doesn't require 16 nights. Different colours of Beds can also be found by visiting a lot of Villages.

**Comment by Joshimuz** [comment]
How can you track which ones you have and haven't slept in?

**Comment by rybak** [comment]
No simple way as far as I can tell. But using [Book and Quill](https://minecraft.gamepedia.com/Book_and_Quill) is always an option.

**Comment by rybak** [comment]
During a stream you have also mentioned replacing some of the "<number> Colour of Beds" goals with "Place <number> Colour of Beds in row".

**Comment by Joshimuz** [comment]
Yeah we don't have that many "Build" goals coz they're hard to define, but place 1 of every colour of bed next to each other is good, but the wording is a big long

**Comment by rybak** [comment]
We can drop "1 of", so "Place every colour of Bed next to each other". Looks short enough:

![image](https://user-images.githubusercontent.com/624072/110925643-bf35cc00-8323-11eb-880b-386ca1d34c9b.png)

**Comment by Joshimuz** [comment]
Yeah looks good, I'm thinking of replacing the every colour of Dye goal in Very Hard with this, since it's just a slightly better version. Maybe a bit easier since you can find Brown sheep (so don't need a jungle) but it does require you get a load of wood and wool too.

**Comment by rybak** [comment]
> replacing the every colour of Dye goal in Very Hard

Another non-Item-goal version of it could be: "Build a full Colour palette out of Glazed Terracotta", meaning a 4x4x1 wall, which includes every colour of Glazed Terracotta.

**Comment by Joshimuz** [comment]
Glazed Terracotta and Concrete just require the dyes and the raw materials for the block, which makes it basically the same as just get the dye. For lower difficulties it makes sense since getting those materials is also part of the challenge, but for Very Hard I don't think it matters. We *could* add every variation of coloured thing but I think just having Beds and Dyes is good enough.
I added Beds and gave it antisyngery with the current Dye goal since the variation is good for Very Hard.
