### ISSUE TITLE
[Bug] Goal "Snowballs" is never generated – possible bug in generator_v3.js

### ISSUE THREAD

**Issue by rybak** [Joshimuz/mcbingo#59]
@WaterArcanum noticed that a Very Easy goal "Snowballs" has tag RareBiome.
However, Very Easy difficulty doesn't allow RareBiome goals:

    RareBiome = {name: "RareBiome", max: [0, 1, 2, 4, 6]}

Easy difficulty ostensibly allows for 1 RareBiome goal. (Note that Easy difficulty uses both Very Easy goals and Easy goals).

It seems that there is a bug in `generator_v3.js` in tag counting. It goes like this:

1. start with: `var tagCount = [1, 1, 1, 1, 1];`
2. count the tags: _something something_ `tagCount[x]++`
3. check the tag's maximum allowed number of goals for the difficulty:

       if (tagCount[x] >= goalCandidate.tags[x].max[difficulty - 1])
           // discard this goal, try another one

During the second step the counts only increase from the `1`s set in the first step. Therefore, all elements in the tagCount array **are always >= 1**.
Tag RareBiome has maximum `1` allowed goal for the Easy difficulty, so in the third step we compare something that is always >=1 and a 1. This seems like a bug.

----

To discover this I've written a function to check for a substring in goal names for all seeds. And "Snowball" never appeared on Easy difficulty. It is available at https://github.com/rybak/mcbingo/commits/check-all-seeds-for-goal

**Comment by Joshimuz** [comment]
It's early in the morning and I don't have much time so I'm trying to understand. What you're saying is that the tag checking doesn't work and should be fixed?

**Comment by rybak** [comment]
Yes. Tag counting starts at one, and should start at zero.

**Comment by Joshimuz** [comment]
OH tagCount is the number of tags on the sheet, I see now, yeah that's me being stupid

**Comment by Joshimuz** [comment]
![image](https://user-images.githubusercontent.com/1105710/110591119-915c5600-8170-11eb-8795-fa533080d153.png)
Wonderful, I wonder how many issues that was causing.
