### ISSUE TITLE
[NEW GOAL] Spawn a Baby Chicken without breeding

### ISSUE THREAD

**Issue by rybak** [Joshimuz/mcbingo#63]
**Name of the Goal**
Couple of options:
- "Spawn a Baby Chicken without breeding"
- "Spawn a Chicken without breeding" 
- "Spawn a Baby Chicken without using Seeds" (bad, because you should be allowed to lure Chickens with Seeds)

**Tooltip for the Goal**
"You've got to crack a few eggs."

**Difficulty level**
Easy. Goal "16 Chicken Eggs" is currently an Easy goal. Per [Minecraft Wiki page "Eggs"](https://minecraft.gamepedia.com/Egg#Spawning_chickens):

> When thrown by a dispenser or by pressing the use button, an egg has a 1⁄8 chance of spawning a chick.

So throwing 16 Eggs is expected to hatch 2 chicks (not counting the rare 4 chicks spawn).

**Anti Synergies and Catalysts/Reactants**
Anti synergy with "16 Eggs".

**Why this Goal is good**
It is a unique breeding method for animals. _Side note:_ Chickens were "breedable" slightly longer than other animals – since [Java Edition Beta 1.0](https://minecraft.gamepedia.com/Java_Edition_Beta_1.0). Regular breeding was added in [Beta 1.9 Prerelease 2](https://minecraft.gamepedia.com/Java_Edition_Beta_1.9_Prerelease_2).

If a 4 chicks spawn happens, it would be rare and funny.

It is a simple goal that fits the difficulty level and it does not take up inventory.

**Comment by Joshimuz** [comment]
Wouldn't "Hatch a Chicken from an Egg" be way better wording?

**Comment by rybak** [comment]
> Wouldn't "Hatch a Chicken from an Egg" be way better wording?

Sure, why not. I was just trying to not mention eggs in the name. Also, "Hatch a Chicken from an Egg" doesn't need a tooltip.

> Also I wouldn't give it anti synergy with Egg goals, that's just good routing

Ok.
