### ISSUE TITLE
Feature request: Clear color on the goals by pressing Q

### ISSUE THREAD

**Issue by Lordmau5** [Joshimuz/mcbingo#67]
Being able to press 1-6 for different colors is nice and all, but seeing as 0 is on the exact opposite end of the keyboard it's a bit difficult to reach without moving one of your hands too far.

Yes, this is nitpicky, but I feel Q might be a good substitute for that when hovering over a goal.

**Comment by Joshimuz** [comment]
Wow look at Lordmau suggesting changes but not implementing them themselves, tut tut tut...
But yes jokes aside this makes sense, as long as it's in addition to 0 (which is how andry implemented it)
