### ISSUE TITLE
[NEW GOAL] Empty a water cauldron, don't use a bucket or glass bottle

### ISSUE THREAD

**Issue by tduva** [Joshimuz/mcbingo#73]
**Name of the Goal**
Empty a water cauldron, don't use a bucket or glass bottle

**Tooltip for the Goal**
None

**Tooltip Image**
None

**Difficulty level**
Easy or Medium (it's not difficult when you know about it)

**Anti Synergies and Catalysts/Reactants**
None

**Why this Goal is good**
It's an variant/extension to "Fill a Cauldron with Water", but also requires learning/knowning about a game mechanic. There's two different ways (as far as I know) to do it, so that's interesting as well.

**Comment by rybak** [comment]
> Easy or Medium (it's not difficult when you know about it)

For reference, "Fill a Cauldron with Water" is currently an Easy goal.

> There's two different ways (as far as I know) to do it, so that's interesting as well.

1. Put an entity on fire (yourself, a mob, items, even arrows in Java edition) on fire and extinguish them in the cauldron.
2. Wash a banner or coloured leather armour in the cauldron.

**Comment by Joshimuz** [comment]
Could it be renamed to "Empty a Cauldron without a Bucket or a Bottle"?
Same thing but shorter, no need to list water, I guess we could also remove water from the other Cauldron.
Maybe causes issues with Bedrock players since they can use non-water liquids

**Comment by rybak** [comment]
Either goal name might need a tooltip "You can fill the Cauldron using Buckets or Bottles."

**Comment by tduva** [comment]
> 
> 
> Either goal name might need a tooltip "You can fill the Cauldron using Buckets or Bottles."

Seems like a good precaution, although maybe "You can *fill* the Cauldron any way you like". So it doesn't sound like it couldn't e.g. be rain.
