### ISSUE TITLE
[NEW GOAL] Have an Endermite kill an Enderman

### ISSUE THREAD

**Issue by PhintiasDarkwood** [Joshimuz/mcbingo#79]
**Name of the Goal**
Have an Endermite kill an Enderman

**Tooltip for the Goal**
If a mob attacks an endermite, any endermites in the area become hostile toward that mob.

**Difficulty level**
Very Hard

**Anti Synergies and Catalysts/Reactants**
Pacifist makes it harder, but not impossible because of trades.

**Why this Goal is good**
> Is it cool or funny?

Yes, little cute thing kills big scary thing.
> Does it teach the player about an interesting or niche game mechanic?

Yes, see tooltip.
> Will it force players to think carefully about their plan?

Kind of?
> Can it give knowledgeable players an edge?

Ender farm knowledge would be useful.
> Or is it just a simple goal that fits the Difficulty well?

Well you convinced me that this goal belongs here so sure?

**Comment by Joshimuz** [comment]
I wouldn't straight up write the solution in the tooltip, especially for a Very Hard goal.
Knowing that Endermites have group aggroing makes this goal actually reasonable to add though, that's a cool mechanic which makes this good, it also sounds really funny to try to achieve.
