### ISSUE TITLE
[NEW GOAL] Save a Snow Golem in the Nether

### ISSUE THREAD

**Issue by WaterArcanum** [Joshimuz/mcbingo#82]
**Name of the Goal**
`Save a Snow Golem in the Nether`
`Prevent a Snow Golem's death in the Nether`
`Have a Snow Golem survive in the Nether for 30 seconds`
These names are all pretty terrible, either non-descriptive or too long. Please feel free to suggest other names.

**Tooltip for the Goal**
`Make sure that the Snow Golem can survive in the Nether without immediately burning down.`
Needs some work done too.

**Difficulty level**
My guess for this goal would be `Hard`, as it requires creating a Snow Golem (thus a rare biome) and brewing / bartering for a splash potion of Fire Resistance.

**Anti Synergies and Catalysts/Reactants**
`Create a Snow Golem`

**Why this Goal is good**
I think this goal is good because it can teach the player about the very niche interactions between said things. One being that Snow Golems burn down in the Nether immediately (and also in other warm biomes, but we need (or just want) more Nether goals), another being that they don't if they have the Fire Resistance effect.
One downside I can think of however is that the time between creating the Snow Golem and it dying a horrible and painful death is about 2 whole seconds, which means it can be a bit frustrating. Luckily, getting the resources for one is the hard part and you can usually collect multiple Pumpkins and Snow Blocks.

**Comment by Joshimuz** [comment]
Yeah the names are horrible, like what does "Save" or "Prevent a death" mean *exactly*. Like if I jump in front of an arrow is that Saving it?
Maybe just explicitly saying use a Fire Res Potion on it would be better, but I'm not sure how interesting it is. I didn't know it before I read this so it's interesting to know but not super interesting to *do* for how hard it is. Putting a Fish into Nether is funny and easy, this I'm not so sure

**Comment by WaterArcanum** [comment]
Point taken, goal not interesting enough to compensate for its difficulty and no proper name for it was given.
