### ISSUE TITLE
EverySword and EveryPickaxe are still missing Stone variants

### ISSUE THREAD

**Issue by WaterArcanum** [Joshimuz/mcbingo#83]
```
{name: "Wooden, Gold, Iron and Diamond Sword", infrequency: 2, antisynergy: ["EverySword"], tags: [Item]},
{name: "Wooden, Gold, Iron and Diamond Pickaxe", infrequency: 2, antisynergy: ["EveryPickaxe"], tags: [Item]},
```
I am aware these goals are supposed to keep their difficulty from before 1.16, therefore aren't specifically referred to as `Every`-type, however I believe the Stone variants of a Sword and Pickaxe should be added to the list.

**Comment by Joshimuz** [comment]
oh rite lol
