### ISSUE TITLE
generator_v3: count the tags using a dictionary

### ISSUE THREAD

**Issue by rybak** [Joshimuz/mcbingo#98]
Currently, `generator_v3.js`, re-counts the tags for every candidate goal. [Quote from Discord](https://discord.com/channels/131720430326120449/819186365085253673/822433684769865768):

> Everytime it makes a new goal, it goes through every singe goal already on the sheet and compares the tags between them. If they match then it adds 1 to x in tagCount, x being the index of the tag on the goal.
> Then after checking every goal it checks if tagCount is too high, then throws the goal away if it is and starts again

Instead, we could keep a single tag counting dictionary, where counts are recorded using tag names. 
[Quote from Discord](https://discord.com/channels/131720430326120449/819186365085253673/822433176764153876):

> Should just have a global tag count for all the tags and add 1 whenever 1 is successfully put on the sheet
> And if it's too big then make a new goal

Something like this:

```js
var tagCount = {};
for (const tag of tags) // list `tags` doesn't exist yet in `goals_v4.js`
{
    tagCount[tag.name] = 0;
}
...

for (var i = 0; i<=24; i++)
{
    // generate goal number `i`
    ...
    currentSheet[i] = goal;
    for (const tag of currentSheet[i].tags)
    {
        tagCount[tag.name]++;
    }
}
```

**Comment by Joshimuz** [comment]
Should we just make a list of tags in goals_v4.js?
```var Item = {name: "Item", max: [25, 25, 20, 20, 20]},
Stat = {name: "Stat", max: [5, 5, 5, 5, 5]}...

var TagList = {Item, Stat... }```

**Comment by rybak** [comment]
Yes, that what the comment "list `tags` doesn't exist yet in `goals_v4.js`" is about.

**Comment by Joshimuz** [comment]
o rite
